/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Client': RouteRecordInfo<'Client', '/client', Record<never, never>, Record<never, never>>,
    'ClientHome': RouteRecordInfo<'ClientHome', '/client', Record<never, never>, Record<never, never>>,
    'Collection': RouteRecordInfo<'Collection', '/client/collection', Record<never, never>, Record<never, never>>,
    'CurrentGame': RouteRecordInfo<'CurrentGame', '/client/game', Record<never, never>, Record<never, never>>,
    'Gifts': RouteRecordInfo<'Gifts', '/client/gifts', Record<never, never>, Record<never, never>>,
    'Lobbies': RouteRecordInfo<'Lobbies', '/client/lobby', Record<never, never>, Record<never, never>>,
    'Lobby': RouteRecordInfo<'Lobby', '/client/lobby/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'Matchmaking': RouteRecordInfo<'Matchmaking', '/client/matchmaking', Record<never, never>, Record<never, never>>,
    'Sandbox': RouteRecordInfo<'Sandbox', '/client/sandbox', Record<never, never>, Record<never, never>>,
    'SelectMode': RouteRecordInfo<'SelectMode', '/client/select-mode', Record<never, never>, Record<never, never>>,
    'TutorialHome': RouteRecordInfo<'TutorialHome', '/client/tutorial', Record<never, never>, Record<never, never>>,
    'TutorialMission': RouteRecordInfo<'TutorialMission', '/client/tutorial/missions/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'HowToPlay': RouteRecordInfo<'HowToPlay', '/client/tutorial/rules', Record<never, never>, Record<never, never>>,
    'WatchGame': RouteRecordInfo<'WatchGame', '/client/watch/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'Home': RouteRecordInfo<'Home', '/', Record<never, never>, Record<never, never>>,
    'Login': RouteRecordInfo<'Login', '/login', Record<never, never>, Record<never, never>>,
    'Register': RouteRecordInfo<'Register', '/register', Record<never, never>, Record<never, never>>,
  }
}
