export type Config = {
  FEATURES: {
    RUNES: boolean;
  };

  MAX_MAIN_DECK_SIZE: number;
  MAX_MAIN_DECK_CARD_COPIES: number;

  INITIAL_HAND_SIZE: number;
  MAX_HAND_SIZE: number;

  CARDS_DRAWN_PER_TURN: number;
  PLAYER_1_CARDS_DRAWN_ON_FIRST_TURN: number;
  PLAYER_2_CARDS_DRAWN_ON_FIRST_TURN: number;

  SHUFFLE_DECK_ON_GAME_START: boolean;

  MAX_RESOURCE_ACTIONS_PER_TURN: number;

  MAX_MANA: number;
  MANA_REGEN_PER_TURN: number;

  MAX_MULLIGANED_CARDS: number;
  MAX_REPLACES_PER_TURN: number;
  MAX_MOVEMENT_PER_TURN: number;
  MAX_ATTACKS_PER_TURN: number;
  MAX_COUNTERATTACKS_PER_TURN: number;
  MAX_EQUIPPED_ARTIFACTS: number;
  DRAW_STEP: 'turn-start' | 'turn-end';

  PLAYER_MAX_HP: number;

  GENERAL_DEPLOY_COOLDOWN: number;
  GENERAL_INITIAL_DEPLOY_COOLDOWN: number;

  PLAYER_MAX_LEVEL: number;
  EXP_PER_LEVEL: number;
  EXP_GAIN_PER_TURN: number;
  EXP_GAIN_PER_GENERAL_ATTACK: number;
};

export const defaultConfig: Config = {
  FEATURES: {
    RUNES: false
  },
  MAX_MAIN_DECK_SIZE: 40,
  MAX_MAIN_DECK_CARD_COPIES: 3,
  INITIAL_HAND_SIZE: 4,
  MAX_HAND_SIZE: 7,
  SHUFFLE_DECK_ON_GAME_START: true,
  CARDS_DRAWN_PER_TURN: 2,
  PLAYER_1_CARDS_DRAWN_ON_FIRST_TURN: 1,
  PLAYER_2_CARDS_DRAWN_ON_FIRST_TURN: 1,
  MAX_MANA: 8,
  MANA_REGEN_PER_TURN: 5,
  MAX_MULLIGANED_CARDS: 0,
  MAX_REPLACES_PER_TURN: 1,
  MAX_MOVEMENT_PER_TURN: 1,
  MAX_ATTACKS_PER_TURN: 1,
  MAX_COUNTERATTACKS_PER_TURN: Infinity,
  MAX_EQUIPPED_ARTIFACTS: 5,
  DRAW_STEP: 'turn-start',
  MAX_RESOURCE_ACTIONS_PER_TURN: 1,

  PLAYER_MAX_HP: 25,

  GENERAL_DEPLOY_COOLDOWN: 2,
  GENERAL_INITIAL_DEPLOY_COOLDOWN: 1,

  PLAYER_MAX_LEVEL: 4,
  EXP_PER_LEVEL: 3,
  EXP_GAIN_PER_TURN: 1,
  EXP_GAIN_PER_GENERAL_ATTACK: 1
};
