export type Config = {
  MAX_MAIN_DECK_SIZE: number;
  MAX_MAIN_DECK_CARD_COPIES: number;
  INITIAL_HAND_SIZE: number;
  MAX_HAND_SIZE: number;
  CARDS_DRAWN_PER_TURN: number;
  PLAYER_1_CARDS_DRAWN_ON_FIRST_TURN: number;
  PLAYER_2_CARDS_DRAWN_ON_FIRST_TURN: number;
  SHUFFLE_DECK_ON_GAME_START: boolean;
  PLAYER_1_INITIAL_MANA: number;
  PLAYER_2_INITIAL_MANA: number;
  MAX_MANA: number;
  MANA_INCREASE_PER_TURN: number;
  MAX_MULLIGANED_CARDS: number;
  MAX_MOVEMENT_PER_TURN: number;
  MAX_ATTACKS_PER_TURN: number;
  MAX_COUNTERATTACKS_PER_TURN: number;
  MAX_EQUIPPED_ARTIFACTS: number;
  DEFAULT_UNIT_SPEED: number;
  DRAW_STEP: 'turn-start' | 'turn-end';
  GENERAL_ABILITY_ENABLED: boolean;
  GENERAL_ABILITY_MAX_USES: number;
  GENERAL_ABILITY_COOLDOWN: number;
};

export const defaultConfig: Config = {
  MAX_MAIN_DECK_SIZE: 40,
  MAX_MAIN_DECK_CARD_COPIES: 3,
  INITIAL_HAND_SIZE: 5,
  MAX_HAND_SIZE: 999,
  SHUFFLE_DECK_ON_GAME_START: true,
  CARDS_DRAWN_PER_TURN: 2,
  PLAYER_1_CARDS_DRAWN_ON_FIRST_TURN: 0,
  PLAYER_2_CARDS_DRAWN_ON_FIRST_TURN: 0,
  PLAYER_1_INITIAL_MANA: 2,
  PLAYER_2_INITIAL_MANA: 3,
  MAX_MANA: 9,
  MANA_INCREASE_PER_TURN: 1,
  MAX_MULLIGANED_CARDS: 3,
  MAX_MOVEMENT_PER_TURN: 1,
  MAX_ATTACKS_PER_TURN: 1,
  MAX_COUNTERATTACKS_PER_TURN: 1,
  MAX_EQUIPPED_ARTIFACTS: 3,
  DEFAULT_UNIT_SPEED: 2,
  DRAW_STEP: 'turn-end',
  GENERAL_ABILITY_ENABLED: true,
  GENERAL_ABILITY_MAX_USES: 1,
  GENERAL_ABILITY_COOLDOWN: 0
};
