export type Config = {
  MAX_MAIN_DECK_SIZE: number;
  MAX_MAIN_DECK_CARD_COPIES: number;

  INITIAL_HAND_SIZE: number;
  MAX_HAND_SIZE: number;

  CARDS_DRAWN_PER_TURN: number;
  PLAYER_1_CARDS_DRAWN_ON_FIRST_TURN: number;
  PLAYER_2_CARDS_DRAWN_ON_FIRST_TURN: number;

  SHUFFLE_DECK_ON_GAME_START: boolean;

  MAX_RESOURCE_ACTIONS_PER_TURN: number;

  PLAYER_1_INITIAL_MANA: number;
  PLAYER_2_INITIAL_MANA: number;
  MAX_MANA: number;
  MAX_OVERSPENT_MANA: number;
  MAX_MANA_INCREASE_PER_TURN: number;

  MAX_MULLIGANED_CARDS: number;
  MAX_REPLACES_PER_TURN: number;
  MAX_MOVEMENT_PER_TURN: number;
  MAX_ATTACKS_PER_TURN: number;
  MAX_COUNTERATTACKS_PER_TURN: number;
  MAX_EQUIPPED_ARTIFACTS: number;
  UNIT_MOVEMENT_REACH: number;
  UNIT_SPRINT_REACH: number;
  DRAW_STEP: 'turn-start' | 'turn-end';
  GENERAL_ABILITY_ENABLED: boolean;
  GENERAL_ABILITY_MAX_USES: number;
  GENERAL_ABILITY_COOLDOWN: number;
  VICTORY_POINT_GOAL: number;
  SHRINE_CAPTURE_VICTORY_POINT_REWARD: number;
  SHRINE_HOLDING_VICTORY_POINT_REWARD_PER_TURN: number;
  GENERAL_DESTROYED_VICTORY_POINTS_REWARD: number;
};

export const defaultConfig: Config = {
  MAX_MAIN_DECK_SIZE: 40,
  MAX_MAIN_DECK_CARD_COPIES: 3,
  INITIAL_HAND_SIZE: 3,
  MAX_HAND_SIZE: 6,
  SHUFFLE_DECK_ON_GAME_START: true,
  CARDS_DRAWN_PER_TURN: 2,
  PLAYER_1_CARDS_DRAWN_ON_FIRST_TURN: 0,
  PLAYER_2_CARDS_DRAWN_ON_FIRST_TURN: 1,
  PLAYER_1_INITIAL_MANA: 2,
  PLAYER_2_INITIAL_MANA: 3,
  MAX_MANA: 9,
  MAX_OVERSPENT_MANA: 0,
  MAX_MULLIGANED_CARDS: 0,
  MAX_REPLACES_PER_TURN: 1,
  MAX_MOVEMENT_PER_TURN: 1,
  MAX_ATTACKS_PER_TURN: 1,
  MAX_COUNTERATTACKS_PER_TURN: Infinity,
  MAX_EQUIPPED_ARTIFACTS: 3,
  UNIT_MOVEMENT_REACH: 2,
  UNIT_SPRINT_REACH: 2,
  DRAW_STEP: 'turn-end',
  GENERAL_ABILITY_ENABLED: false,
  GENERAL_ABILITY_MAX_USES: 1,
  GENERAL_ABILITY_COOLDOWN: 0,
  VICTORY_POINT_GOAL: 1,
  SHRINE_CAPTURE_VICTORY_POINT_REWARD: 0,
  SHRINE_HOLDING_VICTORY_POINT_REWARD_PER_TURN: 0,
  GENERAL_DESTROYED_VICTORY_POINTS_REWARD: 6,
  MAX_RESOURCE_ACTIONS_PER_TURN: 1,
  MAX_MANA_INCREASE_PER_TURN: 1
};
