import { ONE_DAY_IN_SECONDS, ONE_MINUTE_IN_MS } from '@game/shared';

export const DEFAULT_SESSION_TOTAL_DURATION_MS = ONE_DAY_IN_SECONDS * 30 * 1000;
export const SESSION_VERIFICATION_INTERVAL_MS = ONE_MINUTE_IN_MS * 60;
export const INITIAL_MMR = 1200;
export const PASSWORD_MIN_LENGTH = 6;
export const PASSWORD_MAX_LENGTH = 100;
